version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "file-import-state-machine"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nwoa2660e34"
s3_prefix = "file-import-state-machine"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SourceObjectKey=\"eDNE_Delta_Basico_2102.zip\" EnvName=\"cafmf\""
