version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-csv-files-to-sql"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nwoa2660e34"
s3_prefix = "sam-csv-files-to-sql"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FileRepositoryBucketName=\"file-repository-bucket\" EnvName=\"cafmf\""
confirm_changeset = true
